### ISSUE TITLE
primary_key_and_all_references_to_uuid does not find all references

### ISSUE THREAD

**Issue by claracodes** [kreatio-sw/webdack-uuid_migration#15]
I tried to use `primary_key_and_all_references_to_uuid` to transfer all foreign keys of my `devices` table but only 2 out of 3 where found. The query in https://github.com/kreatio-sw/webdack-uuid_migration/blob/2fe705672a09aab0de00de55985e35e7614e7def/lib/webdack/uuid_migration/schema_helpers.rb#L9 would only find 2 instead all three foreign keys.

Any hints on what it could be? 
I eventually transfered everything successfully with a combination of `primary_key_and_all_references_to_uuid` and `columns_to_uuid` but I am curious on why it wouldn't find the third reference in the first place.

**Comment by kum-deepak** [comment]
Wow! After a long time, any issue got raised in this project.

Rails, in older versions, did not create foreign keys for associations automatically. This behavior was added sometime in Rails 4.2. See the original issue reference https://github.com/kreatio-sw/webdack-uuid_migration/issues/4

This library only finds the foreign keys that were actually created at the Postgres database. There may be the following reasons why the foreign key would not be created in the Postgres database:

- Some migrations were executed as older Rails version migrations,
- or, the missing ones were created without using `references`.

Regardless of the reason, the solution you chose is the correct one.

An optional reading below:

You can inspect the database schema (before and after UUID migration) by using Postgres specific tools. If you see that the database actually had all the three foreign keys please let me know.

If you find that the database only had two foreign keys, you can create the third one using Rails Migrations.

**Comment by claracodes** [comment]
Thanks for verifying that I chose the correct solution.

All three table were created in a Rails version of Rails 5.2 or higher, but the difference is that the table that was missed only used 'references` in the migration and does not have `foreign_key: true`.
So rather than `references` it must be explictly labeled as a foreign key.

Thanks for the clarification and the great work with this gem! So easy to use!
