### ISSUE TITLE
Loosen the activerecord (~> 4.0) dependencies

### ISSUE THREAD

**Issue by dlupu** [kreatio-sw/webdack-uuid_migration#3]
Hy, I'm in the process of migrating a rails application from 4.2 to 5.0 and I was wondering if you'd have the time to add compatibility with activerecord 5.0.

**Comment by kum-deepak** [comment]
Today tested with activerecord 5.0.0.beta1. Good news is that it works as is.

You can use directly use from rails5 branch like below:

gem 'webdack-uuid_migration', :git => 'https://github.com/kreatio-sw/webdack-uuid_migration.git', :branch => 'rails5'


Complicated is that tear-down of the test cases is not working. So, when all tests are run sequentially few of those will fail. While individually each case passes.

So, it can safely be used, though I will not push the changes in master until I figure out how to rework the test cases.

This version has only one change from the master - relaxing gem dependency:
spec.add_dependency 'activerecord', '~> 5.0.0.beta1'

Let me know if you face any issues.

**Comment by kum-deepak** [comment]
Updated the test cases. It should work out of the box. Released a new version 1.0.1.

Kindly test.

**Comment by dlupu** [comment]
Worrks perfectly! Thanks
