### ISSUE TITLE
Foreign key constraints in database cause error

### ISSUE THREAD

**Issue by willjohnson** [kreatio-sw/webdack-uuid_migration#4]
With Rails 4.2 if you create a reference via the command line such as:

rails g migration AddUserToUploads user:references

it creates a migration file that adds a foreign key constraint in postgresql. So the original helper primary_key_to_uuid would fail because postgres will not allow changing the column type of a column that has a foreign key constraint on it.

**Comment by kum-deepak** [comment]
I will look into this in about 2 weeks.

**Comment by polysics** [comment]
I am looking for a workaround too. Any luck?

**Comment by kum-deepak** [comment]
Finally I could figure out a way to solve the issue. I have added one more call that will upgrade the primary key and all referring columns.

I have pushed a new version with this, please section 'Schema with Foreign Key References' in the README.

Internally it will query the database to find all tables & columns referring to this primary key as foreign keys and do the following:

-     Drop all foreign key constraints referring to this primary key
-     Convert the primary key to UUID
-     Convert all referring columns to UUID
-     Restore all foreign keys

Please test and let me know if it works.

**Comment by kum-deepak** [comment]
Did any of you got chance to test the new version?

Thanks in advance.

**Comment by obsidienne** [comment]
The version does not work 'cities' is still in the source
PG::UndefinedTable: ERROR:  relation "cities" does not exist
```
/User/.gem/ruby/2.2.4/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:654:in `method_missing'
/User/.gem/ruby/2.2.4/gems/webdack-uuid_migration-1.0.2/lib/webdack/uuid_migration/schema_helpers.rb:5:in `foreign_keys_into'
/User/.gem/ruby/2.2.4/gems/webdack-uuid_migration-1.0.2/lib/webdack/uuid_migration/helpers.rb:92:in `primary_key_and_all_references_to_uuid'
```

**Comment by kum-deepak** [comment]
Released a new version. Please check.
