### ISSUE TITLE
Support for enable_extension "pg_crypto"  with default as "gen_random_uuid()" instead?

### ISSUE THREAD

**Issue by KelseyDH** [kreatio-sw/webdack-uuid_migration#7]
[Apparently this is now the new favoured approach for generating uuid's within postgres for a database](https://github.com/rails/rails/pull/21327/files), and lets people dodge a lot of maintenance issues that existed with `enable_extension 'uuid-ossp'`, at least from what I've read online.

It seems your gem allows the default to be set for the primary_key specific override, which is pretty awesome forethought, but not for the table level override.

**Comment by KelseyDH** [comment]
I added a PR at #8 as an optimistic go of switching the uuid generation strategy over.

**Comment by kum-deepak** [comment]
Released as 1.2.0 of the Gem. Thanks once again.
