### ISSUE TITLE
Instead of padding 0's, can I use altogether new uuids

### ISSUE THREAD

**Issue by railsdeveloper11** [kreatio-sw/webdack-uuid_migration#9]
I don't want to pad 0's in the left of my id column values; instead I want to have the new uuids for them and I still need to migrate them in the associated models i.e wherever they are already associated. Is it possible to do that?

**Comment by kum-deepak** [comment]
It should be possible. The approach I would see will involve saving entity/table_name, old_id (numeric), new_id (uuid) in a table and use it to update relationships. If your schema has foreign keys (references) defined, by using appropriate options, you may cascade updates of primary keys - which would simplify the task. Manual work would still be needed for polymorphic associations.

Currently maintainers of this project will not be able to work on this request. Please go through the code, it has reasonable test case coverage. Will be very kind of you if you are able to raise a Pull Request.
